Access и Accounting не дружат с GraalVM
Error on node access
javax.script.ScriptException: org.graalvm.polyglot.PolyglotException: ReferenceError: importPackage is not defined
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:183)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:168)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at ru.bitel.bgbilling.kernel.application.server.Application.processBean(Application.java:474)
        at ru.bitel.bgbilling.kernel.application.server.Application.process(Application.java:376)
        at ru.bitel.bgbilling.kernel.application.server.Application.processChildren(Application.java:829)
        at ru.bitel.bgbilling.kernel.application.server.Application.application(Application.java:268)
        at ru.bitel.bgbilling.kernel.application.server.Application.<init>(Application.java:174)
        at ru.bitel.bgbilling.kernel.application.server.Application.main(Application.java:883)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at ru.bitel.common.bootstrap.Boot.boot(Boot.java:129)
        at ru.bitel.common.bootstrap.Boot.main(Boot.java:178)
Caused by: org.graalvm.polyglot.PolyglotException: ReferenceError: importPackage is not defined
        at <js>.:program(eval-source:1)
        at org.graalvm.polyglot.Context.eval(Context.java:311)
        at com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.eval(GraalJSScriptEngine.java:181)
        ... 14 more